
# Config file for automatic testing at travis-ci.org

language: python
p
ython:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - pytest

after_success:
  - coveralls